name: Renovate

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * MON" #Every MON 10:00 AM AEST


  
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Substitute vars
        shell: bash
        run: sed -i "s/GITHUB_TOKEN/${{ secrets.GITHUB_DEPLOYMENT_PAT }}/g" config.json
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.107.1
        with:
          configurationFile: config.json
          token: ${{ secrets.GITHUB_DEPLOYMENT_PAT }}
        env:
          LOG_LEVEL: 'debug'
